blank_issues_enabled: false
contact_links:
  - name: "💡 Suggest a feature"
    url: https://github.com/magit/forge/discussions
    about: Start a discussion suggest an improvement or a new feature.
  - name: "🆘 Ask the community for support"
    url: https://www.reddit.com/r/emacs
    about: Please also consider supporting others.
  - name: "🆘 Ask the maintainers for support"
    url: https://github.com/magit/forge/discussions
    about: Please keep in mind that our bandwidth is limited.
  - name: "ℹ️ Forge FAQ"
    url: https://magit.vc/manual/forge/FAQ.html
    about: Others might have had the same question before.
  - name: "ℹ️ Forge Manual"
    url: https://magit.vc/manual/forge/#Top
    about: The fine manual may also be of use.
